2014-06-27 10:00:57,587 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 10:03:54,705 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 10:03:55,675 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 10:03:55,675 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 10:04:23,907 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 10:04:23,907 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 10:04:23,907 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 10:11:47,003 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 10:19:22,459 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 10:22:21,947 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 10:22:21,947 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 11:13:11,134 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Birthday.py", line 19, in handle
    oauth_access_token = profile['keys']["FB_TOKEN"]
KeyError: 'keys'
2014-06-27 11:35:36,169 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 12:20:41,704 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 12:47:19,965 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 13:51:01,988 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 13:51:01,988 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 13:52:08,918 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 13:52:08,918 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 13:52:08,918 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 13:52:43,905 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 13:52:43,905 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 13:52:43,905 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
2014-06-27 13:52:43,905 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 78, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Notifications.py", line 19, in handle
    oauth_access_token = profile['keys']['FB_TOKEN']
KeyError: 'keys'
